### ISSUE TITLE
Article Cover stacked with Article description

### ISSUE THREAD

**Issue by rahmanramsi** [madi-nuralin/material#1]
![image](https://user-images.githubusercontent.com/48276043/132315293-8b8aead5-4edb-4574-adcf-b369a677fd7e.png)

**Comment by madi-nuralin** [comment]
There was a new release of the plugin which contains fix of this issue, so could you update or reinstall plugin in order to make sure the issue was fixed?

**Comment by rahmanramsi** [comment]
Yes, it fixed. Thanks.
