### ISSUE TITLE
Is there any way to remove the spinner/website loading animation?

### ISSUE THREAD

**Issue by ShubashBiswas** [madi-nuralin/material#13]
I found the page is already loaded but the spinner/website loading animation hides the page until it's complete. The Journal takes more time to load on the first visit. But when I scrolled I saw the text below. Please take a look at the file I've attached. I think removing the spinner/website loading animation will improve website performance. 
![Screenshot](https://github.com/madi-nuralin/material/assets/79921627/fe2ae331-bdef-47a6-b550-0ff572a39fc6)

**Comment by madi-nuralin** [comment]
Hi @ShubashBiswas 
Spinner preloader waits for all page elements to be loaded. Especially, sometimes background images took a lot of time due to networking issues.
Btw, you can remove spinner animation just by removing lines below in `templates/frontend/components/footer.tpl` file.

```html
		<div class="html-preloader bg-light">
			<div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
				<span class="visually-hidden">Loading...</span>
			</div>
		</div>
```
