### ISSUE TITLE
Unable to install manually by FTP or Cpanel

### ISSUE THREAD

**Issue by amirhfro** [madi-nuralin/material#14]
Greetings and Regards
Due to the use of shared hosting, I am not able to activate "exec" function in my hosting and I cannot use the quick installation feature. I installed it manually from FTP and CPanel (I copied the material folder file into the OJS themes folder). When opening the website management plugins section, I get stuck in an infinite loading loop and then get error 500.
What is correct way of Manual installation?

**Comment by madi-nuralin** [comment]
Hi @amirhfro 
I'm sorry for the delay. 
Could you provide ojs version, and material theme version which you are trying to install?)
