### ISSUE TITLE
Request to change username to username and email on the login page.

### ISSUE THREAD

**Issue by ShubashBiswas** [madi-nuralin/material#16]
Dear @madi-nuralin 

As I am testing OJS 3.4.0-4. We can now log in to OJS via email input. Could you update the log in via email on the login page? Changing **username** to **Username or Email *** will be more suitable and understandable. 

Avobe the Username or Email * an indication of Required fields is marked with an asterisk: * will be more helpful for users.

![Login](https://github.com/madi-nuralin/material/assets/79921627/4b604436-ce64-4ed4-9c65-ae589b0703ce)

**Comment by madi-nuralin** [comment]
Hi @ShubashBiswas !
Thank you for your suggestion!
Your request will be considered in release [v2_2_1-0](https://github.com/madi-nuralin/material/milestone/6).
