### ISSUE TITLE
Theme Redesign (v3)

### ISSUE THREAD

**Issue by madi-nuralin** [madi-nuralin/material#17]
The 'Material Theme' plugin is based on MDB library and it has limitations and constraints to adapt website design to scientific journals' style. It is decided to switch to the 'Tailwind CSS Framework', which provides more flexibility and to develop a new plugin design which mostly respond to the OJS manner.

To-Do List:
- [x] Remove MDB
- [x] Setup TailwindCSS
- [x] Setup Alpine js
- [x] Design theme

**Comment by ShubashBiswas** [comment]
Dear @madi-nuralin 
That's a piece of great news. I am suggesting adding Dark Mode if possible as no other OJS theme supports Dark Mode. Adding a dark mode button will be a good addition.

**Comment by TheBigGoldenEagle** [comment]
Hello, thank you for 

> @madi-nuralin

Hello, thank you very much for such a great theme. Do you have any estimate as to when v3 will be released?

**Comment by madi-nuralin** [comment]
Hi @TheBigGoldenEagle 

For the moment, it is quite challenging for me to estimate a release time of the theme, due to I'm developing a new design only at my rest time. I hope by the end of February to commit minor version.
