### ISSUE TITLE
it does not work on Journal main page

### ISSUE THREAD

**Issue by Nour-Dw** [madi-nuralin/material#22]
the them is working on the Journal as child but not at the main page
For example, I have tow Journal on OJS system, so the main page/home page of the Journals them does not working with it

![Untitled](https://github.com/madi-nuralin/material/assets/165440563/02a59dd9-187e-45e4-b736-2868fe8b789b)

**Comment by madi-nuralin** [comment]
Thank you for reporting the problem. If it's necessary for you I could provide fix patch for v2 to resolve this bug. However, for now v3 theme (#17) is under development, then you may wait for 3_0_0 release, but v3 is totally different from v2. So material_v2* is no longer be supported in future.

**Comment by Nour-Dw** [comment]
Hello @madi-nuralin 

thank you very much for the beautiful theme

I will be grateful if you could provide me a fix patch for v2 to resolve this bug

Thank again for the theme & help

**Comment by madi-nuralin** [comment]
Hi!
Sorry for delay;)
So finally it looks like:
![image](https://github.com/madi-nuralin/material/assets/77335604/0d08a57a-45b6-45c8-b6ba-eb5847e7af6d)

You can get update from main branch (just download project as zip or tar archive, then replace the plugin folder), as i'm going to open PR.

**Comment by Nour-Dw** [comment]
Hello @madi-nuralin 

Thanks for your updated, I have updated the files and it's working on main site, but the Language menu does not show

Can you please let me know how to fix the Language option to be showing with same way as the template is displayed it on the journal pages

FYI, I had to removed this line "{include file="frontend/objects/announcements_list.tpl" numAnnouncements=$numAnnouncementsHomepage}" from indexSite.tpl file as it wasn't work with this line


We appreciate your help, Thanks
