### ISSUE TITLE
Recaptcha V 2 issue on user registration and login. 

### ISSUE THREAD

**Issue by munir-abbasi** [madi-nuralin/material#24]
I was trying to enable recaptcha on the above two pages and was having issues with material theme. 
A little bit of googling lead me to the solution for material theme. 

please put in the following code in userLogin.tpl and userRegister.tpl

`{* recaptcha spam blocker *}
		{if $recaptchaPublicKey}
			<fieldset class="recaptcha_wrapper">
				<div class="fields">
					<div class="recaptcha">
						<div class="g-recaptcha" data-sitekey="{$recaptchaPublicKey|escape}">
						</div>
					</div>
				</div>
			</fieldset>
		{/if}`

the code is from [this link](https://github.com/pkp/bootstrap3/commit/0834bd5fbace98e7b8f298655ca189261a03eaf5) and I have tested it in my material theme with OJS 3.4.x It works.  

Could u please add it to the above mentioned two files? 

Thanks

**Comment by madi-nuralin** [comment]
Closed due to PRs #25, #26
