### ISSUE TITLE
there is a empty space when open in mobile device 

### ISSUE THREAD

**Issue by powersaint** [madi-nuralin/material#32]
hi sir, 
im using ojs version  OJS 3.3.0.17, and using the newer version, 

there is and empty space so the menu wont show up 

![ss 1](https://github.com/madi-nuralin/material/assets/117619639/c2fae566-c86a-4a8b-a8fd-e91ed790f75b)

**Comment by ardaniblam** [comment]
and how to change the colour gradient background ? i have to back to the default theme to change the colour ?

thank you

**Comment by ardaniblam** [comment]
and also how to add language in the theme ?

**Comment by powersaint** [comment]
where do i can se the version of plugin that i installed ?

im installing with the plugin in the website menu, in the dashboard, 

in my samsung note 8, iphone x it show there is a white space in the ui, and i cant see the menu because the menu in the right side, and the empty space is white,

i tested in tablet its normal 
![image](https://github.com/madi-nuralin/material/assets/117619639/7d7ede09-bffd-4c7f-8b76-3d39c119b054)

**Comment by madi-nuralin** [comment]
Hi!

> where do i can se the version of plugin that i installed ?

Click "Plugin Galley" tab, then find and click "Material Theme"  link. You should see something like:
![image](https://github.com/madi-nuralin/material/assets/77335604/6c251af1-559a-4451-a6eb-5ab911f8e77e)

**Comment by madi-nuralin** [comment]
I've tested in Chrome and Mozilla with Iphone XR screen emulator and didn't find such bug.

![photo_5287778944323542435_x](https://github.com/madi-nuralin/material/assets/77335604/f5ea6380-ad85-4cba-a019-1f6ec1323de6)

I suppose the problem is in browser and it's compatabilty with MDB(https://mdbootstrap.com/) library
