### ISSUE TITLE
Articles Title not showing in the page

### ISSUE THREAD

**Issue by vzrenggamani** [madi-nuralin/material#37]
Hello, nice to having this theme installed in out Journal, its sleek and elegant ofcourse, but we had a slight problems here.

![image](https://github.com/madi-nuralin/material/assets/14950309/9cfc9f19-dcd7-4521-9400-6f301184bc6f)
https://journal.teknologipendidikan.or.id/index.php/jetsar/article/view/2

The Article title are not showing entirely, we already doing reinstall in the theme and it does not work. Can you help us investigate this issues?

P.S: We use two language (english and indonesia), will that cause some issues?

**Comment by madi-nuralin** [comment]
Hi,
Thank you for reporting issue.
#### Quick fix.
You can search for the file:
`material/templates/frontend/objects/
/article_details.tpl` on your ojs installation project and remove comment brackets (`{*` and `*}` respectively) from 90 and 92 lines:
```smarty
{*<h1 class="page_title">
	{$publication->getLocalizedTitle(null, 'html')|strip_unsafe_html}
</h1>*}
```

#### or
You may wait for a week while I commit changes to pkp plugin gallery, so you can simply update plugin for the newer version (v3_0_1-0).

**Comment by vzrenggamani** [comment]
Thank you for the responses, I think i will gonna wait for the fix to make sure everything stable. 
Thank you for the nice and hard works! 💯

**Comment by madi-nuralin** [comment]
![image](https://github.com/madi-nuralin/material/assets/77335604/f9ca6cd6-628e-4c9b-b061-cbf593242681)
