### ISSUE TITLE
PDF view rendering is hanging

### ISSUE THREAD

**Issue by serhii-petrenko** [madi-nuralin/material#38]
Hi!
Thanks a lot for all your efforts and the amazing theme!

**Material theme enable**

![m1](https://github.com/madi-nuralin/material/assets/23415440/b8016168-3a5b-40e8-a7e6-1d7ca1e2fe82)

**Material theme disabled**

2 screenshots to show all network calls
No. 1
![m2](https://github.com/madi-nuralin/material/assets/23415440/6936c8a8-b3ad-4507-814d-133bfb77d074)
No. 2
![m3](https://github.com/madi-nuralin/material/assets/23415440/3fafaeb3-c4f2-4aeb-a385-71f0f9718862)

**Configurations**
OJS version    3.4.0.5
PHP version	8.3.8
PDF.JS PDF Viewer  https://github.com/pkp/pdfJsViewer/tree/stable-3_4_0

**Comment by madi-nuralin** [comment]
Hi!
Thank you for reporting the issue.
Recently I switched to TailwindCSS framework, and for now it's quite challenging to integrate stylesheet which is provided by another plugin.
I'm planning to overwrite pdfJsViewer's style wi

**Comment by madi-nuralin** [comment]
The reason of pdf viewer fault is that material theme comes without jquery lib.
As a result, the jquery will be included only when previewing pdf.

![image](https://github.com/madi-nuralin/material/assets/77335604/0da7d403-d978-40cc-9f56-4cbe5fb7e042)
