### ISSUE TITLE
eror msg on submit new issue

### ISSUE THREAD

**Issue by rizki554** [madi-nuralin/material#45]
hello Dev, can u help me to fix this eror after trying to publish new Issue

**Comment by rizki554** [comment]
##plugins.themes.default.displayStats.downloads##

**Comment by madi-nuralin** [comment]
Hi!
> ##plugins.themes.default.displayStats.downloads##
Could you provide screenshot of problem page and ojs, material theme version?)

**Comment by rizki554** [comment]
https://lmappi.org/index.php/simcoem/article/view/2
![lmappi error](https://github.com/user-attachments/assets/110b04a2-19ea-4b67-8afa-e242b849cd62)

**Comment by madi-nuralin** [comment]
Hi!
Actually that section is only for default plugin theme. It was decided to remove displayStats.
You can get updates from the main branch or wait for the v3_0_2-0 release.
