### ISSUE TITLE
Archve listing on home page

### ISSUE THREAD

**Issue by asifdev124** [madi-nuralin/material#5]
@madi-nuralin how can we get the list of archives on the home page? for example 8 most recent issues to be displayed on the home page, just the cover and the title, 4 in a row, can you please send me code snippet? 

or may be list of articles from 4 given issues to be displayed in grid on home page, just title, author, issue number?
thank you in advance

**Comment by madi-nuralin** [comment]
In my opinion, this kind of functionality is not considered by ojs team itself, but generally it could be implemented, while it's a complicated slightly. 
TODO:
1) In ```MaterialThemePlugin.inc.php``` file you need to load archive records from db and send to smarty template
2) In smarty template (```indexJournal.tpl```) file just iterate those array of archives and display it as you wish in a form of grid or smth. else etc.
It looks like I can add this functionality to project, if it's not urgent for you, as there are few more accumulated suggestions from other users, so in the coming days I'm going to start to prepare for new minor release of the project. I can consider your proposal if you'll to wait a bit.

**Comment by asifdev124** [comment]
@madi-nuralin its all okay, I can wait for your final update.A portion on the home page where user can put the most viewed and cited articles, and obviously, user may control this if he/she wanted to enable this on the home page, thank you!

**Comment by madi-nuralin** [comment]
> @madi-nuralin how can we get the list of archives on the home page? for example 8 most recent issues to be displayed on the home page, just the cover and the title, 4 in a row, can you please send me code snippet?
> 
> or may be list of articles from 4 given issues to be displayed in grid on home page, just title, author, issue number? thank you in advance

@asifdev124, sorry for delay, this feature was added to the latest release, you may check https://github.com/madi-nuralin/material/releases/tag/v2_0_1-0
