### ISSUE TITLE
When trying to deploy the layout, the link with the theme name appears:

### ISSUE THREAD

**Issue by Jeffersonbr88** [madi-nuralin/material#8]
Hello. 

When trying to deploy the layout, the link with the theme name appears:

![image](https://github.com/madi-nuralin/material/assets/141047760/430a2363-0263-4a3e-acec-cd1e074e756f)

how to solve?

**Comment by madi-nuralin** [comment]
Hi!

Could you tell me which locale are you using and ojs version?) It doesn't seem to be supported by the theme yet. You may checkout: https://github.com/madi-nuralin/material/tree/main/locale. If the necessary localisation folder is not there, you may just create a new one for that locale and translate strings.

Btw, I'll include missing locales for upcoming release.

**Comment by Jeffersonbr88** [comment]
Thanks.
